# Load data

In [1]:
import yfinance as yf
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
headers = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64)"}

sp500_df = pd.read_html(url, storage_options=headers)[0]
sp500_tickers = sp500_df['Symbol'].str.replace('.', '-',regex=False).rename('ticker')

sp500_tickers

0       MMM
1       AOS
2       ABT
3      ABBV
4       ACN
       ...
498     XYL
499     YUM
500    ZBRA
501     ZBH
502     ZTS
Name: ticker, Length: 503, dtype: str

In [3]:
sp500_path = Path('../config/sp500_tickers.csv')
sp500_path.parent.mkdir(parents=True, exist_ok=True)
sp500_tickers.to_csv(sp500_path, index=False)

In [4]:
raw = yf.download(tickers=sp500_tickers.tolist(), start='2010-01-01', auto_adjust=False, actions=True, group_by='ticker')
raw

[*********************100%***********************]  503 of 503 completed

Ticker            DASH                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2010-01-04         NaN         NaN         NaN         NaN         NaN
2010-01-05         NaN         NaN         NaN         NaN         NaN
2010-01-06         NaN         NaN         NaN         NaN         NaN
2010-01-07         NaN         NaN         NaN         NaN         NaN
2010-01-08         NaN         NaN         NaN         NaN         NaN
...                ...         ...         ...         ...         ...
2026-09-21  193.850006  194.949997  188.710007  193.830002  193.830002
2026-09-22  198.044998  200.585007  191.979996  192.210007  192.210007
2026-09-23  190.630005  191.360001  184.850006  189.270004  189.270004
2026-09-24  189.000000  192.559998  182.139999  187.529999  187.529999
2026-09-25  187.820007  193.669998  187.529999  193.360001  193.360001

Ticker                                              BIIB              ...  \
Price          Volume Dividends Stock Splits        Open        High  ...
Date                                                                  ...
2010-01-04        NaN       NaN          NaN   53.970001   53.970001  ...
2010-01-05        NaN       NaN          NaN   54.720001   55.000000  ...
2010-01-06        NaN       NaN          NaN   53.099998   53.700001  ...
2010-01-07        NaN       NaN          NaN   53.230000   53.500000  ...
2010-01-08        NaN       NaN          NaN   53.000000   54.330002  ...
...               ...       ...          ...         ...         ...  ...
2026-09-21  5054500.0       0.0          0.0  216.139999  221.919998  ...
2026-09-22  5219100.0       0.0          0.0  219.220001  226.429993  ...
2026-09-23  5832700.0       0.0          0.0  226.940002  229.190002  ...
2026-09-24  5530500.0       0.0          0.0  226.800003  228.720001  ...
2026-09-25  2872400.0       0.0          0.0  228.270004  228.919998  ...

Ticker          EXPD                     ROL                                   \
Price      Dividends Stock Splits       Open       High        Low      Close
Date
2010-01-04       0.0          0.0   3.832099   3.909136   3.808395   3.873580
2010-01-05       0.0          0.0   3.879506   3.885432   3.836049   3.853827
2010-01-06       0.0          0.0   3.845926   3.901235   3.845926   3.855802
2010-01-07       0.0          0.0   3.841975   3.889383   3.800494   3.885432
2010-01-08       0.0          0.0   3.871605   3.889383   3.849877   3.879506
...              ...          ...        ...        ...        ...        ...
2026-09-21       0.0          0.0  32.419998  32.709999  31.879999  32.349998
2026-09-22       0.0          0.0  32.770000  33.099998  32.639999  32.860001
2026-09-23       0.0          0.0  32.720001  33.029999  32.279999  32.490002
2026-09-24       0.0          0.0  31.500000  31.580000  30.120001  30.400000
2026-09-25       0.0          0.0  30.010000  30.340000  29.740000  30.030001

Ticker
Price       Adj Close    Volume Dividends Stock Splits
Date
2010-01-04   3.046337    839363       0.0          0.0
2010-01-05   3.030803    701663       0.0          0.0
2010-01-06   3.032356    841388       0.0          0.0
2010-01-07   3.055659    536119       0.0          0.0
2010-01-08   3.050998    330581       0.0          0.0
...               ...       ...       ...          ...
2026-09-21  32.349998   6589800       0.0          0.0
2026-09-22  32.860001   6338700       0.0          0.0
2026-09-23  32.490002   9239100       0.0          0.0
2026-09-24  30.400000  13646400       0.0          0.0
2026-09-25  30.030001   9264200       0.0          0.0

[4208 rows x 4024 columns]

In [6]:
raw_long = raw.copy().stack(level='Ticker').reset_index()
raw_long.columns.name = None
raw_long.columns = raw_long.columns.str.lower().str.replace(' ', '_', regex=False)
raw_long = raw_long.sort_values(by=['ticker', 'date'])
raw_long

,date,ticker,open,high,low,close,adj_close,volume,dividends,stock_splits
334,2010-01-04,A,22.453505,22.625179,22.267525,22.389128,19.772945,3815561.0,0.0,0.0
837,2010-01-05,A,22.324751,22.331903,22.002861,22.145924,19.558168,4186031.0,0.0,0.0
1340,2010-01-06,A,22.067240,22.174536,22.002861,22.067240,19.488678,3243779.0,0.0,0.0
1843,2010-01-07,A,22.017166,22.045780,21.816881,22.038628,19.463406,3095172.0,0.0,0.0
2346,2010-01-08,A,21.917025,22.067240,21.745352,22.031473,19.457100,3733918.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
2114504,2026-09-21,ZTS,72.059998,72.480003,70.260002,71.330002,71.330002,3942400.0,0.0,0.0
2115007,2026-09-22,ZTS,71.980003,73.459999,71.239998,72.860001,72.860001,3840400.0,0.0,0.0
2115510,2026-09-23,ZTS,72.750000,73.550003,71.550003,71.610001,71.610001,3828600.0,0.0,0.0
2116013,2026-09-24,ZTS,71.849998,72.379997,69.930000,70.269997,70.269997,3369400.0,0.0,0.0
2116516,2026-09-25,ZTS,70.000000,71.080002,69.519997,71.050003,71.050003,4165600.0,0.0,0.0

In [7]:
raw_path = Path('../data/raw/sp500_2010_2026.csv')
raw_path.parent.mkdir(parents=True, exist_ok=True)
raw_long.to_csv(raw_path, index=False)

In [9]:
clean = raw_long.copy().drop_duplicates().dropna(subset='adj_close')
clean['month'] = clean['date'].dt.to_period('M')
clean = clean[clean['month'] < pd.Timestamp.today().to_period('M')]
clean = clean.groupby(by=['ticker', 'month']).tail(1).reset_index(drop=True)

prev_month = clean.groupby('ticker').shift(1)
month_gap = clean['month'].astype('int64') - prev_month['month'].astype('int64')

month_gap

0       -9223372036854775328
1                          1
2                          1
3                          1
4                          1
                ...
94220                      1
94221                      1
94222                      1
94223                      1
94224                      1
Name: month, Length: 94225, dtype: int64

In [11]:
clean['return'] = clean['adj_close'] / prev_month['adj_close'] - 1
clean['return'] = np.where(month_gap!=1, np.nan, clean['return'])
clean['target_return'] = clean.groupby('ticker')['return'].shift(-1)

print("Check duplicates:")
print(clean.duplicated(['ticker','month']).sum())

print("\nCheck missing values:")
print(clean.isna().sum())

clean

Check duplicates:
0

Check missing values:
date               0
ticker             0
open               0
high               0
low                0
close              0
adj_close          0
volume             0
dividends          0
stock_splits       0
month              0
return           503
target_return    503
dtype: int64

,date,ticker,open,high,low,close,adj_close,volume,dividends,stock_splits,month,return,target_return
0,2010-01-29,A,20.693848,20.865522,19.971388,20.050072,17.707222,5923046.0,0.0,0.0,2010-01,NaN,0.122369
1,2010-02-26,A,22.296137,22.546495,22.160229,22.503576,19.874033,4678127.0,0.0,0.0,2010-02,0.122369,0.093134
2,2010-03-31,A,24.713877,24.735336,24.527897,24.599428,21.724976,5293387.0,0.0,0.0,2010-03,0.093134,0.054376
3,2010-04-30,A,26.645206,26.773964,25.915594,25.937054,22.906301,4195678.0,0.0,0.0,2010-04,0.054376,-0.107557
4,2010-05-28,A,23.433475,23.497854,23.004292,23.147352,20.442572,3430692.0,0.0,0.0,2010-05,-0.107557,-0.121446
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94220,2026-04-30,ZTS,114.040001,115.540001,113.790001,114.970001,114.174103,4297200.0,0.0,0.0,2026-04,-0.023178,-0.324258
94221,2026-05-29,ZTS,78.510002,78.879997,77.440002,77.690002,77.152184,9295100.0,0.0,0.0,2026-05,-0.324258,-0.075042
94222,2026-06-30,ZTS,73.169998,73.559998,71.470001,71.860001,71.362541,8322200.0,0.0,0.0,2026-06,-0.075042,0.083061
94223,2026-07-31,ZTS,75.610001,77.519997,74.910004,77.290001,77.290001,5018300.0,0.0,0.0,2026-07,0.083061,-0.002458
94224,2026-08-31,ZTS,77.000000,77.209999,75.620003,77.099998,77.099998,5798800.0,0.0,0.0,2026-08,-0.002458,NaN

In [12]:
clean_path = Path('../data/interim/monthly_panel.csv')
clean_path.parent.mkdir(parents=True, exist_ok=True)
clean.to_csv(clean_path, index=False)

In [13]:
clean.groupby('ticker')['return'].count().describe()

count    503.000000
mean     186.326044
std       36.040828
min        2.000000
25%      199.000000
50%      199.000000
75%      199.000000
max      199.000000
Name: return, dtype: float64