# Load data

In [60]:
import yfinance as yf
import numpy as np
import pandas as pd
from pathlib import Path

In [61]:
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
headers = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64)"}

sp500_df = pd.read_html(url, storage_options=headers)[0]
sp500_tickers = sp500_df['Symbol'].str.replace('.', '-',regex=False).rename('ticker')

sp500_tickers

0       MMM
1       AOS
2       ABT
3      ABBV
4       ACN
       ...
498     XYL
499     YUM
500    ZBRA
501     ZBH
502     ZTS
Name: ticker, Length: 503, dtype: str

In [62]:
sp500_path = Path('../config/sp500_tickers.csv')
sp500_path.parent.mkdir(parents=True, exist_ok=True)
sp500_tickers.to_csv(sp500_path, index=False)

In [63]:
raw = yf.download(tickers=sp500_tickers.tolist(), start='2010-01-01', auto_adjust=False, actions=True, group_by='ticker')
raw

[*********************100%***********************]  503 of 503 completed

Ticker            HONA                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2010-01-04         NaN         NaN         NaN         NaN         NaN
2010-01-05         NaN         NaN         NaN         NaN         NaN
2010-01-06         NaN         NaN         NaN         NaN         NaN
2010-01-07         NaN         NaN         NaN         NaN         NaN
2010-01-08         NaN         NaN         NaN         NaN         NaN
...                ...         ...         ...         ...         ...
2026-09-21  163.850006  170.320007  163.000000  169.029999  169.029999
2026-09-22  168.979996  169.270004  166.029999  167.320007  167.320007
2026-09-23  166.699997  168.500000  161.570007  163.330002  163.330002
2026-09-24  161.570007  163.970001  158.289993  158.460007  158.460007
2026-09-25  159.009995  160.970001  156.740005  158.779999  158.779999

Ticker                                              EXPE              ...  \
Price          Volume Dividends Stock Splits        Open        High  ...
Date                                                                  ...
2010-01-04        NaN       NaN          NaN   51.419998   51.820000  ...
2010-01-05        NaN       NaN          NaN   51.500000   52.060001  ...
2010-01-06        NaN       NaN          NaN   51.459999   51.759998  ...
2010-01-07        NaN       NaN          NaN   49.560001   49.799999  ...
2010-01-08        NaN       NaN          NaN   49.200001   49.200001  ...
...               ...       ...          ...         ...         ...  ...
2026-09-21  3974700.0       0.0          0.0  279.290009  283.649994  ...
2026-09-22  3873700.0       0.0          0.0  285.250000  287.119995  ...
2026-09-23  2976400.0       0.0          0.0  278.000000  278.000000  ...
2026-09-24  2765500.0       0.0          0.0  260.549988  268.140015  ...
2026-09-25  2285000.0       0.0          0.0  262.149994  269.260010  ...

Ticker             T                     LEN                                   \
Price      Dividends Stock Splits       Open       High        Low      Close
Date
2010-01-04      0.00          0.0  12.193485  12.393378  12.041186  12.383860
2010-01-05      0.00          0.0  12.326747  12.945464  12.107817  12.897871
2010-01-06      0.42          0.0  12.859796  13.088245  12.612309  13.040652
2010-01-07      0.00          0.0  14.211455  15.229958  13.916374  14.715947
2010-01-08      0.00          0.0  14.658835  15.296589  14.458941  15.182364
...              ...          ...        ...        ...        ...        ...
2026-09-21      0.00          0.0  76.980003  78.379997  76.500000  78.080002
2026-09-22      0.00          0.0  81.000000  83.370003  80.180000  83.059998
2026-09-23      0.00          0.0  82.000000  83.190002  81.309998  81.519997
2026-09-24      0.00          0.0  81.190002  81.980003  80.120003  81.470001
2026-09-25      0.00          0.0  82.000000  82.269997  80.370003  82.150002

Ticker
Price       Adj Close    Volume Dividends Stock Splits
Date
2010-01-04  10.693975   4721011       0.0          0.0
2010-01-05  11.137845   6518836       0.0          0.0
2010-01-06  11.261141   6684720       0.0          0.0
2010-01-07  12.707827  30160976       0.0          0.0
2010-01-08  13.110595   9078423       0.0          0.0
...               ...       ...       ...          ...
2026-09-21  78.080002   4951200       0.0          0.0
2026-09-22  83.059998   6465100       0.0          0.0
2026-09-23  81.519997   5863600       0.0          0.0
2026-09-24  81.470001   4781200       0.0          0.0
2026-09-25  82.150002   3890800       0.0          0.0

[4208 rows x 4024 columns]

In [64]:
raw_long = raw.copy().stack(level='Ticker').reset_index()
raw_long.columns.name = None
raw_long.columns = raw_long.columns.str.lower()
raw_long = raw_long.sort_values(by=['ticker', 'date'])
raw_long

,date,ticker,open,high,low,close,adj close,volume,dividends,stock splits
327,2010-01-04,A,22.453505,22.625179,22.267525,22.389128,19.772957,3815561.0,0.0,0.0
830,2010-01-05,A,22.324751,22.331903,22.002861,22.145924,19.558168,4186031.0,0.0,0.0
1333,2010-01-06,A,22.067240,22.174536,22.002861,22.067240,19.488672,3243779.0,0.0,0.0
1836,2010-01-07,A,22.017166,22.045780,21.816881,22.038628,19.463406,3095172.0,0.0,0.0
2339,2010-01-08,A,21.917025,22.067240,21.745352,22.031473,19.457087,3733918.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
2114500,2026-09-21,ZTS,72.059998,72.480003,70.260002,71.330002,71.330002,3942400.0,0.0,0.0
2115003,2026-09-22,ZTS,71.980003,73.459999,71.239998,72.860001,72.860001,3840400.0,0.0,0.0
2115506,2026-09-23,ZTS,72.750000,73.550003,71.550003,71.610001,71.610001,3828600.0,0.0,0.0
2116009,2026-09-24,ZTS,71.849998,72.379997,69.930000,70.269997,70.269997,3369400.0,0.0,0.0
2116512,2026-09-25,ZTS,70.000000,71.080002,69.519997,71.050003,71.050003,4165600.0,0.0,0.0

In [65]:
raw_path = Path('../data/raw/sp500_2010_2026.csv')
raw_path.parent.mkdir(parents=True, exist_ok=True)
raw_long.to_csv(raw_path, index=False)

In [66]:
clean = raw_long.copy().drop_duplicates().dropna(subset='adj close')
clean['month'] = clean['date'].dt.to_period('M')
clean = clean[clean['month'] < pd.Timestamp.today().to_period('M')]
clean = clean.groupby(by=['ticker', 'month']).tail(1).reset_index(drop=True)

prev_month = clean.groupby('ticker').shift(1)
month_gap = clean['month'].astype('int64') - prev_month['month'].astype('int64')

month_gap

0       -9223372036854775328
1                          1
2                          1
3                          1
4                          1
                ...
94220                      1
94221                      1
94222                      1
94223                      1
94224                      1
Name: month, Length: 94225, dtype: int64

In [70]:
clean['return'] = clean['adj close'] / prev_month['adj close'] - 1
clean['return'] = np.where(month_gap!=1, np.nan, clean['return'])
clean['target_return'] = clean.groupby('ticker')['return'].shift(-1)

print("Check duplicates:")
print(clean.duplicated(['ticker','month']).sum())

print("\nCheck missing values:")
print(clean.isna().sum())

clean

Check duplicates:
0

Check missing values:
date               0
ticker             0
open               0
high               0
low                0
close              0
adj close          0
volume             0
dividends          0
stock splits       0
month              0
return           503
target_return    503
dtype: int64

,date,ticker,open,high,low,close,adj close,volume,dividends,stock splits,month,return,target_return
0,2010-01-29,A,20.693848,20.865522,19.971388,20.050072,17.707218,5923046.0,0.0,0.0,2010-01,NaN,0.122369
1,2010-02-26,A,22.296137,22.546495,22.160229,22.503576,19.874029,4678127.0,0.0,0.0,2010-02,0.122369,0.093134
2,2010-03-31,A,24.713877,24.735336,24.527897,24.599428,21.724983,5293387.0,0.0,0.0,2010-03,0.093134,0.054376
3,2010-04-30,A,26.645206,26.773964,25.915594,25.937054,22.906298,4195678.0,0.0,0.0,2010-04,0.054376,-0.107557
4,2010-05-28,A,23.433475,23.497854,23.004292,23.147352,20.442575,3430692.0,0.0,0.0,2010-05,-0.107557,-0.121446
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94220,2026-04-30,ZTS,114.040001,115.540001,113.790001,114.970001,114.174103,4297200.0,0.0,0.0,2026-04,-0.023178,-0.324258
94221,2026-05-29,ZTS,78.510002,78.879997,77.440002,77.690002,77.152184,9295100.0,0.0,0.0,2026-05,-0.324258,-0.075042
94222,2026-06-30,ZTS,73.169998,73.559998,71.470001,71.860001,71.362541,8322200.0,0.0,0.0,2026-06,-0.075042,0.083061
94223,2026-07-31,ZTS,75.610001,77.519997,74.910004,77.290001,77.290001,5018300.0,0.0,0.0,2026-07,0.083061,-0.002458
94224,2026-08-31,ZTS,77.000000,77.209999,75.620003,77.099998,77.099998,5798800.0,0.0,0.0,2026-08,-0.002458,NaN

In [68]:
clean_path = Path('../data/interim/monthly_panel.csv')
clean_path.parent.mkdir(parents=True, exist_ok=True)
clean.to_csv(clean_path, index=False)

In [69]:
clean.groupby('ticker')['return'].count().describe()

count    503.000000
mean     186.326044
std       36.040828
min        2.000000
25%      199.000000
50%      199.000000
75%      199.000000
max      199.000000
Name: return, dtype: float64